### ISSUE TITLE
Generating a WF instance model from a generic WF

### ISSUE THREAD

**Issue by MireilleBF** [MireilleBF/FromMLWFConfigurationToBPMN#6]
Etant donné un WF générique

Attention cette issue suppose de fixer des règles de modélisation avant.
Ci-après une première proposition qui peut être modifier.

**Proposition :** 

- une tâche générique se termine par _Step_, (eg.  _preprocessing_Step_). Elle correspond forcément dans le FM à une feature abstraite de même nom.

- une instance de tâche générique non définie 
          - commence par #, ce qui interdit donc d'utiliser cette notation pour une tâche concrète. 
          - dans la description, contient _refersTo:_ Nom de la tâche générique associée (eg. refersTo:  preprocessing_Step)
          - Pour éviter des doublons dans les noms des features une feature fille a dans son nom une référence au feature pere (pas très joli... mais sinon on va avoir des problèmes)

**TODO**

1. - [x]  Générer un WF instance dans lequel tous les tâches génériques (ex. preprocessing_Step) sont remplacés par des tâches comme : #preprocessing#1_ avec un _refersTo_ _preprocessing_Step_

2. - [x]  L'utilisateur peut alors modifier un WF instance en remplaçant les tâches générées par des tâches propres
       - [x] Une seule tâche par tâche générique 
       - [x] puis possibilité de définir plusieurs tâches liées pour une tâche générique
3. - [x]  Exprimer des contraintes telles que : 
      - [x]  des ordres entre les tâches : _t1 > t2_ qui signifie que la tâche t1 doit toujours s'exécuter avant la tache t2 etc.
      - [x]  des implications entre les tâches _detectWith_OC_SVM => training_OC_SVM_  
4. - [x]  Toutes les tâches concrètes peuvent être remontées dans le FM comme un feature fille concrete du feature abstrait correspond à la tâche générique : 
        - [x] eg. une tâche concrete _t1 refersTo: preprocessing_Step_ deviendra un feature concrete de nom __t1_preprocessing_,_ fille de la feature _preprocessing_Step_
        - [x] si la feature existe déjà, elle n'est pas remontée, évidemment
5. - [x]  Dans un premier temps, remonter dans le FM, un feature dont le nom correspond au nouveau WF tel que, ce feature implique :
        - [x]  La selection du WF générique correspondant
        - [x]  La sélection de toutes les tâches concretes
L'objectif est de vérifier la cohérence du WF, et dans le même temps de garder en mémoire ces expériences. Mais attention, ce n'est absoluement pas l'objectif final, donc il doit être possible de retirer du FM de telles informations facilement.
